### ISSUE TITLE
cannot prepare data 

### ISSUE THREAD

**Issue by nazib** [mcahny/vps#21]
hi
I tried to prepare data descriped in dataset.md. After running the bash command for fetching I am getting this error:
my command: 
python prepare_data/fetch_city_images.py --src_dir /home/nazib/Data/leftImg8bit/val/ --dst_dir /home/nazib/Data/cityscapes_vps/ --mode SPLIT

output:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nazib/Data/cityscapes_vps/panoptic_im_SPLIT_city_vps.json'

I couldn't find that json file after unzipping the cityscapes_vps data

**Comment by abdur75648** [comment]
Hey @nazib , did you download the leftImg8bit.zip file from the CityScapes data?
I would be really thankful if you share a link to just the "val" split of it as I'm having trouble downloading 325 GBs of whole file

**Comment by RaduCorcodel** [comment]
Hi @nazib did you solve the missing file problem? I'm having the same error

Radu,

**Comment by mcahny** [comment]
Please see **# For SPLIT = 'train'/'val'/'test'**
```
# For SPLIT = 'train'/'val'/'test'
python prepare_data/fetch_city_images.py \
...
```
