### ISSUE TITLE
Confusion about epoch setting

### ISSUE THREAD

**Issue by EDENpraseHAZARD** [mcahny/vps#8]
Hi mcahny,
I found the settings of training epoch in the code is diiferent from the settings in the paper.
In the paper, set 12 epochs for VIPER and set 144 epochs for CS-VPS.(shown in the picture)

![image](https://user-images.githubusercontent.com/53077461/91021547-83a51000-e626-11ea-88b4-0ba135d14f30.png)

But the code you provided set 12 epochs for the CS-VPS dataset. 

![image](https://user-images.githubusercontent.com/53077461/91021870-f44c2c80-e626-11ea-8b01-046e74fc3068.png)

Is that only a fine-tuned process in the code?

**Comment by mcahny** [comment]
The dataloader “RepeatDataset” repeats the dataset 8 times which makes the effective epoch that many more. 

+ the total epoch in the config.py should be 18 (decay at 12 and 16 epoch) , which will be 8x18=144 effective epochs.

**Comment by EDENpraseHAZARD** [comment]
Thank you very much!
