### ISSUE TITLE
Cityscapses-VPS images

### ISSUE THREAD

**Issue by emjay73** [mcahny/vps#9]
At where can I download original images of cityscape-VPS?
I found annotated GT images from the link on the github but I can not find original sequential images, not even from the Cityscapes website.

**Comment by emjay73** [comment]
Nevermind. I found out that It is available upon request.

**Comment by abdur75648** [comment]
Hey @emjay73,
Where did you find the images for Cityscape-VPS?

The "leftImg8bit.zip" file on the website is 325 GBs! Did you download it?
If yes, I would be really thankful if you could share a link to just the "val" split of it as I'm having trouble downloading it
